language: python
python:
  - "2.7"
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
install:
  - pip install tox
script:
  - tox -e $TOX_ENV term-missing

notifications:
  email:
    on_success: never
    on_failure: change
